---------------------------------------
Begin Slurm Prolog: Feb-19-2025 10:26:32
Job ID:    2817795
User ID:   jshim87
Account:   gts-vfung3
Job name:  MattersimRunner
Partition: gpu-a100
QOS:       inferno
---------------------------------------
Input Notebook:  mattersim_runner.ipynb
Output Notebook: mattersim_runner.out.ipynb
Executing:   0%|          | 0/7 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:  14%|█▍        | 1/7 [00:02<00:14,  2.50s/cell]Executing:  29%|██▊       | 2/7 [00:09<00:25,  5.00s/cell]Executing:  86%|████████▌ | 6/7 [00:55<00:10, 10.13s/cell]Executing:  86%|████████▌ | 6/7 [00:58<00:09,  9.73s/cell]
Traceback (most recent call last):
  File "/storage/home/hcoda1/7/jshim87/.conda/envs/graph_partitioning/bin/papermill", line 8, in <module>
    sys.exit(papermill())
             ^^^^^^^^^^^
  File "/storage/home/hcoda1/7/jshim87/.conda/envs/graph_partitioning/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/hcoda1/7/jshim87/.conda/envs/graph_partitioning/lib/python3.11/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/storage/home/hcoda1/7/jshim87/.conda/envs/graph_partitioning/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/hcoda1/7/jshim87/.conda/envs/graph_partitioning/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/hcoda1/7/jshim87/.conda/envs/graph_partitioning/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/hcoda1/7/jshim87/.conda/envs/graph_partitioning/lib/python3.11/site-packages/papermill/cli.py", line 235, in papermill
    execute_notebook(
  File "/storage/home/hcoda1/7/jshim87/.conda/envs/graph_partitioning/lib/python3.11/site-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/storage/home/hcoda1/7/jshim87/.conda/envs/graph_partitioning/lib/python3.11/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [5]":
---------------------------------------------------------------------------
PapermillExecutionError                   Traceback (most recent call last)
Cell In[5], line 2
      1 for param in trials:
----> 2     pm.execute_notebook("mattersim.ipynb", output_file, parameters=param)
      3     append_nb_data()

File ~/.conda/envs/graph_partitioning/lib/python3.11/site-packages/papermill/execute.py:131, in execute_notebook(input_path, output_path, parameters, engine_name, request_save_on_cell_execute, prepare_only, kernel_name, language, progress_bar, log_output, stdout_file, stderr_file, start_timeout, report_mode, cwd, **engine_kwargs)
    116         nb = papermill_engines.execute_notebook_with_engine(
    117             engine_name,
    118             nb,
   (...)
    127             **engine_kwargs,
    128         )
    130     # Check for errors first (it saves on error before raising)
--> 131     raise_for_execution_errors(nb, output_path)
    133 # Write final output in case the engine didn't write it on cell completion.
    134 write_ipynb(nb, output_path)

File ~/.conda/envs/graph_partitioning/lib/python3.11/site-packages/papermill/execute.py:251, in raise_for_execution_errors(nb, output_path)
    248 nb.cells.insert(0, error_msg_cell)
    250 write_ipynb(nb, output_path)
--> 251 raise error

PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [3]":
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
File ~/.conda/envs/graph_partitioning/lib/python3.11/site-packages/metis.py:430
    429 try:
--> 430     _dll = ctypes.cdll.LoadLibrary(_dll_filename)
    431 except:

File ~/.conda/envs/graph_partitioning/lib/python3.11/ctypes/__init__.py:454, in LibraryLoader.LoadLibrary(self, name)
    453 def LoadLibrary(self, name):
--> 454     return self._dlltype(name)

File ~/.conda/envs/graph_partitioning/lib/python3.11/ctypes/__init__.py:376, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    375 if handle is None:
--> 376     self._handle = _dlopen(self._name, mode)
    377 else:

OSError: /storage/home/hcoda1/7/jshim87/local/lib/libmetis.so: undefined symbol: gk_jbufs

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
Cell In[3], line 10
      6 import torch
      8 from tqdm import tqdm
---> 10 from partitioner import part_graph_extended
     11 import networkx as nx

File ~/atomic-graph-partitioning/partitioner.py:2
      1 import networkx as nx
----> 2 import metis
      4 from collections import deque
      6 def part_graph_extended(G, desired_partitions, distance=None):

File ~/.conda/envs/graph_partitioning/lib/python3.11/site-packages/metis.py:432
    430         _dll = ctypes.cdll.LoadLibrary(_dll_filename)
    431     except:
--> 432         raise RuntimeError('Could not load METIS dll: %s' % _dll_filename)
    433 else:
    434     if os.environ.get('READTHEDOCS', None) == 'True':
    435         # Don't care if we can load the DLL on RTD.

RuntimeError: Could not load METIS dll: /storage/home/hcoda1/7/jshim87/local/lib/libmetis.so


---------------------------------------
Begin Slurm Epilog: Feb-19-2025 10:27:43
Job ID:        2817795
User ID:       jshim87
Account:       gts-vfung3
Job name:      MattersimRunner
Resources:     cpu=1,gres/gpu:a100=1,mem=80G,node=1
Rsrc Used:     cput=00:01:11,vmem=0,walltime=00:01:11,mem=765220K,energy_used=0
Partition:     gpu-a100
QOS:           inferno
Nodes:         atl1-1-02-018-35-0
---------------------------------------
